#!/bin/bash
export PATH=~/.local/bin:$PATH
export PYTHONUNBUFFERED=1

# request explicit PYTHON
if [ -z "$PYTHON" ]; then
    echo "Please set the PYTHON environment variable to the Python interpreter you want to use."
    exit 1
fi

poetry install --sync --no-root
poetry env use $PYTHON
poetry run python3 -u ./qt6_build.py "$@"
